{% set name = "opentelemetry-instrumentation-dbapi" %}
{% set version = "0.66b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_dbapi-{{ version }}.tar.gz
  sha256: b16a83d1295ba2ba73032a8c01b6b43d9a2b176d5d3c8996773338a2ee08bf2a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.66b0
    - opentelemetry-semantic-conventions ==0.66b0
    - wrapt <3.0.0,>=1.0.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-dbapi
  summary: OpenTelemetry Database API instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
